name: Deploy Static Website to GCS

on:
  push:
    branches:
      - main
    paths:
      - 'static/**' 
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      GCS_BUCKET_NAME: static-website-34296

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Deploy static site to GCS bucket
        run: |
          gsutil -m rsync -r -d ./static gs://${{ env.GCS_BUCKET_NAME }}